<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<!-- استفاده از آخرین نسخه پایدار زبان C# -->

	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
	 
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyManagement.Application.Contract\CompanyManagement.Application.Contract.csproj" />
    <ProjectReference Include="..\CompanyManagement.Infrasructure.EFCore\CompanyManagement.Infrasructure.EFCore.csproj" />
    <ProjectReference Include="..\CompanyManagement.Infrastructure.Configuration\CompanyManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\Framework\Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\CompanyCategories\_CompanyDetails.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Pages\Index.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Theme\assets\fonts\dana\" />
    <Folder Include="wwwroot\Theme\assets\img\etc\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Black.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Bold.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-DemiBold.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-ExtraBlack.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-ExtraBold.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-fat.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Hairline.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Heavy.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Light.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Medium.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-Thin.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\Theme\assets\fonts\woff2\DanaFaNum-UltraLight.woff2" />
  </ItemGroup>

</Project>
